[build]
builder = "nixpacks"
buildCommand = "npm run build"

# Frissítve: 2025-06-26
[deploy]
startCommand = "npm run start:server"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"